### ISSUE TITLE
日期选择控件 先选择早期时间 再选择未来时间  这时候控件点击后 input 不能获取选择的时间问题

### ISSUE THREAD

**Issue by langlangbody** [cheap-pets/mussel#1]
mussel version：
0.1.40

Vue version：
2.6.11

component：
mu-date-editor

问题描述：

日期选择控件 先选择早期时间 再选择未来时间  这时候控件点击后 input 不能获取选择的时间 显示

**Comment by scrollbar-ww** [comment]
谢谢反馈，已经解决，近期随 1.0.6 版本发布。
